language: python
sudo: false
dist: trusty
cache:
  directories:
  - $HOME/.cache/pip
python:
- '3.6'
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=tkoyama010
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=mayavi-doc
  - secure: n5dRw3JmoGJa65wkitGG9W1SQUFfpBNN8yiswGytzSiF1pKya93guaSwOKqUwue+b1c34yy4NVUI9fJfs71+PNJC22BeNSz6klUcqcJX92jP8385GOtegofhSOBVhLkyMTs7pe9HBnQBtjV0vHQGHzEnGGVt+HIK4Cc9yrelhIP7X5S+cCdVDncnVS65dnrAzx1x0La/vk2BBFVjxQD4WMxS5oWrf9d5HhQ/OtBPfxrJUJcg83cFnrboj2AC0EFnbjsUtYUQTYE4VPuwnucZ3oscImttq0hrjOYCQ1Cv3zRCqAQdDsfhxA8IqgHxwFyPdzIw/4LsjvkBWX85soENBPCT1GbIegTFGt9V/4j1AOx64BukXKsfxY/HZV3lYs0YhDJOFx61alDU/Qo60x3VGzMRwfQtLp7TIpupV3w2HXLPoPSF1z8SwCsdUzHIB87+EVgRmQ8vDFb5RxW1yFJ0Etz90agSQ9FGGMkJgUxrRIDIVkzOCIV5VOx9xhjsyE3QXjN6z+5WXqORL3brrmY0NKHspOsnzq807jC5nVYnvkcqlZhyF+IEv0imN/axV/Q7FKFBQZHau9pDJPxwlTcYSyo9jq2wcV997JaxF8GRl0nVaOKMXw/7h5Zdnv1MzUFmDpH2DDYAWCBHk1ACBOnGhu3EBoSR85fBilg0wIM3QwA=
before_install:
- openssl aes-256-cbc -K $encrypted_4f115fd035ba_key -iv $encrypted_4f115fd035ba_iv -in .secrets/key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- git branch -a
- git checkout master  # attach this repo
- git submodule init
- git submodule update
- (cd mayavi; git fetch origin; git checkout devel-tkoyama010; git reset --hard origin/devel-tkoyama010; git branch -a)
- pip install -U pip setuptools
- pip install -r ./requirements.txt
script:
- sh ./locale/update.sh
after_success:
- git branch -a
- git checkout master  # attach this repo
- git config --global user.email "mayavi-auto-update"
- git config --global user.name "mayavi-auto-update"
- git add .
- |
  git commit -m "[skip ci] by Travis CI (JOB $TRAVIS_JOB_NUMBER)
  https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
- git remote -v
- git remote add github git@github.com:getfem-doc/mayavi-doc-translations.git
- git push github master
