language: python
sudo: false
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
python:
- '3.6'
env:
  global:
  - SPHINXINTL_TRANSIFEX_USERNAME=api
  - SPHINXINTL_TRANSIFEX_PROJECT_NAME=mayavi
  - secure: qh2m+h5Lij54MbQloS/xQih8NpiBzTKqoGhYcAd6Bagn7BDxeLQTEyYhPGJPn9TGgKhW9gewmGOGYtjCtWShTYxjRt/h6gUW6WGU2mcNpaLehVBC6JOOC2ACskUFrvKo0Z/frsph4+2I4zR9f+mkk66SZJAzts+XLJrvVQJfh4cMe1s8zb1om3NSRB61Hi0otpQy/HR0lTsTz3bRiWsLPPY6x59N338em3KTWl4N/0b2zbJh4ycejzpjdU9d+oP2TDy4jYaGBQ7FV4SFCZnUVhybBprURFU+Fc/fa+38Px9E+xul57o1vH3wG76qusfZqqpga99qZFL+uIA/hZfhzsRsqLrxXaenQm7IXcgHR8dNfb0zP1+qyortppTAeyKxBfsB6H3qzsoLu6PBuDQyx6DEcXrUct19cHm4PuT8PCXztc/GtWp4rTIfRx3v5RBv9e43CTXjOqkzYYtbCIqqeTd3L8XoUkLUNgOh4+tMi2UF4vv4ah0yeuuMfajSdKeTq40Gv2O3nCUbrwKeUrDBWFw6hqAJXxKhQlzmvCTdKgbuWb+cWTz363rIjXw79G3+5+ECwsqikDYHezsXLAG9L7I7gGvSSX7wlxDmHv2e33axIhBdbRT/JmDhueZvZbdELPyBjMdzgIKxOfXXSmoGUe7kGd9o5MPD8QgnExM6718=
before_install:
- openssl aes-256-cbc -K $encrypted_4f115fd035ba_key -iv $encrypted_4f115fd035ba_iv -in .secrets/key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- git branch -a
- git checkout master  # attach this repo
- git submodule init
- git submodule update
- (cd mayavi; git fetch origin; git checkout patch-7; git reset --hard origin/patch-7; git branch -a)
- pip install -U pip setuptools
- pip install -r ./requirements.txt
script:
- sh ./locale/update.sh
after_success:
- git branch -a
- git checkout master  # attach this repo
- git config --global user.email "mayavi-auto-update"
- git config --global user.name "mayavi-auto-update"
- git add .
- |
  git commit -m "[skip ci] by Travis CI (JOB $TRAVIS_JOB_NUMBER)
  https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
- git remote -v
- git remote add github git@github.com:getfem-doc/mayavi-doc-translations.git
- git push github master
