name: sphinx-auto-update
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
    - name: update
      env:
        ACCOUNT: tkoyama010
        ORGANIZATION: getfem-doc
        NAME: "mayavi-auto-update"
        EMAIL: "mayavi-auto-update"
        REPO: mayavi-doc-translations
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: mayavi
      run: |
        sudo apt-get install python3-venv
        python3 -m venv .venv
        source .venv/bin/activate
        git submodule update
        (cd mayavi; git fetch origin; git checkout master; git reset --hard origin/master; git branch -a)
        pip install -U pip setuptools
        pip install -r ./requirements.txt
        sh ./locale/update.sh
        git branch -a
        git checkout master
        git config --global user.email $EMAIL
        git config --global user.name $NAME
        git add .
        git commit --allow-empty -m ":green_heart: $JOB_ID
        $HTML_URL"
        git remote -v
        git remote set-url origin https://${ACCOUNT}:${{ secrets.GITHUB_PASS }}@github.com/${ORGANIZATION}/${REPO}
        git push origin master
        deactivate
